name: hijri
description: >
  Convert between Hijri Calendar and Gregorian Calendar date support Arabic and English Local.
version: 3.0.1
homepage: https://github.com/alheekmahlib/hijri_date

environment:
  sdk: '>=3.5.3 <4.0.0'


dev_dependencies:
  test: "^1.14.3"