name: hijri_date
description: >
  Enhanced Hijri Calendar library with comprehensive date operations, Islamic
  events,  multi-language support, and advanced utilities for Arabic, English,
  and Turkish locales.
version: 1.1.0
homepage: https://github.com/alheekmahlib/hijri_date
repository: https://github.com/alheekmahlib/hijri_date
issue_tracker: https://github.com/alheekmahlib/hijri_date/issues
documentation: https://github.com/alheekmahlib/hijri_date/blob/master/README.md

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  assets:
    - assets/moon.svg
    - assets/moon_background.svg

topics:
  - hijri
  - islamic-calendar
  - date-conversion
  - arabic
  - islamic-events
