name: hijri_date
description: >
  Enhanced Hijri Calendar library with comprehensive date operations, Islamic events, 
  multi-language support, and advanced utilities for Arabic, English, and Turkish locales.
version: 1.0.0
homepage: https://github.com/alheekmahlib/hijri_date
repository: https://github.com/alheekmahlib/hijri_date
issue_tracker: https://github.com/alheekmahlib/hijri_date/issues
documentation: https://github.com/alheekmahlib/hijri_date/blob/master/README.md

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  # No external dependencies - pure Dart implementation

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

topics:
  - hijri
  - islamic-calendar  
  - date-conversion
  - arabic
  - islamic-events